### ISSUE TITLE
Изменения в базу 1

### ISSUE THREAD

**Issue by quellerusco** [Bodigrim/durmstrang#1]
Добавить в каждую заявку поле выбора игры. Вид:
Поставьте галочку, если вы собираетесь поехать на эту игру:
(окошко для галочки) Дурмштранг: Aqua Mortis (23-28 июня 2016 г.)

Для админов - было бы круто иметь возможность отсортировать заявки по результатам этой отметки

**Comment by Bodigrim** [comment]
После какого пункта добавить в анкету? После какого столбца выводить в общей таблице?

**Comment by quellerusco** [comment]
Последним пунктом в разделе "Игрок".
В таблице - предпоследним столбцом, перед статусом заявки.

**Comment by Bodigrim** [comment]
Вынес. Проверяй.

**Comment by quellerusco** [comment]
Есть, спасибо!
