### ISSUE TITLE
Новый пункт в заявке

### ISSUE THREAD

**Issue by quellerusco** [Bodigrim/durmstrang#10]
Необходимо убрать из заявки (раздел Игрок) пункт "Едете ли вы на Aqua Mortis" и сделать новый:
"Подтвердите заявку на "Дурмштранг: Королевская свадьба" (29 апреля - 6 мая 2017 г.)"

Спасибо

**Comment by Bodigrim** [comment]
Проверь, пожалуйста.

**Comment by quellerusco** [comment]
Работает, спасибо!
