### ISSUE TITLE
Изменения в базу 2

### ISSUE THREAD

**Issue by quellerusco** [Bodigrim/durmstrang#2]
В мастерском поле выбора статуса заявки добавить пункт "Архив" - для заявок людей, вышедших из проекта. 
И возможность отсортировать заявки по статусу, сейчас не получается так сделать.

**Comment by Bodigrim** [comment]
Есть. Проверяй.

**Comment by quellerusco** [comment]
Можно ли сделать так, чтобы при сортировке Архив шел в самом конце списка? Первым "на рассмотрении", потом "утверждена", потом "отклонена", потом "архив"

**Comment by Bodigrim** [comment]
Есть. Подходит?

**Comment by quellerusco** [comment]
Есть, спасибо! Закрывай тикет.
