### ISSUE TITLE
электронные адреса

### ISSUE THREAD

**Issue by quellerusco** [Bodigrim/durmstrang#3]
Хотелось бы чтобы в каждой конкретной заявке выводился e-mail игрока - тот, на который у него подвязан аккаунт. 
Ну и если есть возможность как-то их сразу выгрузить в виде таблицы "игрок - e-mail", тоже будет хорошо.

**Comment by Bodigrim** [comment]
Вынес внутрь заявки. 
В качестве бонуса внизу списка заявок добавил кнопку "Скачать CSV" с полным списком игроков и почт, но Excel почему-то жует кодировку кириллицы (надо указывать Unicode). 
Принято?

**Comment by quellerusco** [comment]
Скачивается таблица с кракозябрами, при закачке нигде нельзя указать Юникод. Как можно его сделать тогда?

**Comment by Bodigrim** [comment]
При открытии CSV в Excel должно показаться окно с выбором разделителей и кодировки. Если оно не показывается, то мне сложно чем-то помочь. Возможно, по каким-то причинам эвристики не срабатывают и Excel считает, что никакой кириллицы в файле нет. Можно попробовать открыть файл в любом текстовом редакторе.

**Comment by quellerusco** [comment]
Да, окно не появляется.
Другими текстовыми редакторами открывается, но результат крайне неудобочитаем.

**Comment by Bodigrim** [comment]
Обходной путь:
1. Переименовать в base.txt.
2. Запустить Эксель.
3. Меню Файл - Открыть. 
4. И вот теперь выбрать кодировку.
5. Результат все равно сомнительной удобоваримости.

К сожалению, с поддержкой CSV все время проблемы. Мне очень неудобно отлаживать этот функционал так, чтобы не читать чужие заявки. На этом тикет закрываю.
