### ISSUE TITLE
Еще одна галочка нужна

### ISSUE THREAD

**Issue by quellerusco** [Bodigrim/durmstrang#4]
Необходим список в разделе Игрок. Виден - админам и игроку, но менять могут только админы. 

"Взнос"
Варианты: 
- не сдан 
- частично сдан
- сдан
- особые условия

**Comment by Bodigrim** [comment]
Выносится ли этот параметр в общую таблицу игроков? Или виден только изнутри профиля?

**Comment by Bodigrim** [comment]
Мне кажется, что просто поле будет малополезно для мастера по АХЧ, он задолбается вручную синхронизироваться со своими записями. Нужна, наверное, как минимум выгрузка таблицы игроков с суммами взносов в Excel. Может пригласить к обсуждению Белку?

**Comment by quellerusco** [comment]
Да, логично. Сейчас приглашу ее сюда.

**Comment by Tiramisy** [comment]
Тек, я тут ) 
Собственно - зачем мне нужна эта галочка. 
В базе ОЧЕНЬ много игроков. И абсолютно непонятно, кто из них будет играть, а кто - нет в этот заход. 
У меня есть табличка Экселя, где ведутся финансовые вопросы - сколько чего докупить, сколько стоит и т.д., общая сумма затрат. В этой же табличке вписываются ФИО игроков, которые сдали - что сдали, сколько и где должны. 
Теперь - у меня есть игрок, который заявился на игру, но ничего не сдал. И найти его в табличке среди кучи народа + разобраться сдал/не сдал - очень сложно. 

В идеале - я бы хотела 2 отметки. 1я - участвует/не участвует в этой игре, 2я - сдал/не сдал.

**Comment by quellerusco** [comment]
Первая отметка уже есть )

**Comment by Tiramisy** [comment]
Просто прописывать в базе суммы взносов - для меня лично бесполезно вообще, потому что эти данные никак не будут связаны с всей бухгалтерией. 
А вот быстро глянуть в базу и написать тем, у кого участие подтверждено, а взнос не сдан - было бы ну оччччень круто!

**Comment by Tiramisy** [comment]
А - да, мне эти галочки нужны именно в общей таблице, чтобы не бегать по провилям всех игроков. 
А еще мну почему-то в базу не пускает (

**Comment by Tiramisy** [comment]
Если реализовывать вариант с 4-мя значениями, то наверное нужна не галочка, а комбик.

**Comment by Bodigrim** [comment]
Вы расходитесь в показаниях :) Решите, пожалуйста, полезны ли вам четыре значения или достаточно галочки сдал/не сдал. При прочих равных я бы делал галочку: а) меньше ширина колонки в основной таблице, б) значение меняется в один клик. 

@Tiramisy как именно в базу не пускает? Только что проверил, вроде нормально.

**Comment by Tiramisy** [comment]
Я за галочку, Руско - за комбик со значениями ) Но если будет комбик - можно и комбик, не вопрос. Лишь бы оно было.

В базу уже пустило. Похоже на какие-то глюки, может - сеть с моей стороны...

**Comment by Bodigrim** [comment]
Решите наконец :) Если пользоваться тебе, то, наверное, надо делать галочку.

**Comment by quellerusco** [comment]
Оно в целом почти полностью для пользования конкретно Белкой, так что пускай уже галочка будет )))

**Comment by Bodigrim** [comment]
Проверяй.

**Comment by Bodigrim** [comment]
Если замечаний не поступит, то я в воскресенье закрою тикет.
