### ISSUE TITLE
Кнопка "Выйти" в заявке

### ISSUE THREAD

**Issue by quellerusco** [Bodigrim/durmstrang#5]
На данный момент кнопка "Выйти" внутри заявки выбрасывает админа вообще из базы.
Можно ли сделать так, чтобы она выводила просто обратно в общую таблицу?

**Comment by Bodigrim** [comment]
Поправил. Подходит?

**Comment by quellerusco** [comment]
Сама кнопка ок, но при выходе в таблицу приходится заново ее сортировать по нужному параметру. 
Можно ли сделать чтобы сортировка сохранялась?

**Comment by Bodigrim** [comment]
Для того, чтобы увидеть предыдущую страницу в том же состоянии, в котором она была, лучше всего воспользоваться кнопкой "Назад" в меню браузера. Или открывать анкеты игроков в новых вкладках.

**Comment by quellerusco** [comment]
при кнопке "Назад" все равно приходится сортировать заново, возможно это настройки браузера влияют.
В общем, если это сложно и муторно сделать - будем открывать отдельными вкладками. Закрывай тикет.
