### ISSUE TITLE
В заявку не подгружается фото

### ISSUE THREAD

**Issue by quellerusco** [Bodigrim/durmstrang#7]
По ссылке те фото, которые попробовал загрузить в заявку
https://pp.vk.me/c629527/v629527730/2e604/TBKtumekeIo.jpg
https://pp.vk.me/c628120/v628120730/5e4c8/a7Pdp4WoCjw.jpg (изначально была в формате .png, но вконтакт залил тоже жпег

**Comment by Bodigrim** [comment]
Загадочно. У меня в мою анкету обе фото загрузились нормально. На всякий случай отключил кэширование фото. Проверь, грузится ли у тебя сейчас. Если нет, то помогает ли обновление страницы? Если нет, то создай временную анкету для экспериментов и проверь, работает ли в ней.

**Comment by quellerusco** [comment]
В мою все так же не подгружается, обновление страницы не помогает - зато в общей таблице выскакивает оповещение, что я обновил заявку. Создал временную заявку - в нее все подгрузилось с первого раза.

**Comment by Bodigrim** [comment]
Перепроверь еще раз, пожалуйста. У меня проблема не воспроизводится.

**Comment by quellerusco** [comment]
Перепроверил, все по прежнему.

**Comment by Bodigrim** [comment]
Исправлено.
