### ISSUE TITLE
Новый статус

### ISSUE THREAD

**Issue by quellerusco** [Bodigrim/durmstrang#8]
Пожалуйста, сделай в вариантах статуса для персонажа еще один пункт - "Другое"

**Comment by Bodigrim** [comment]
Это точно хорошая идея? Для чего вам такой статус? 

Каким должен быть порядок сортировки статусов заявок? Сейчас так: сначала "на рассмотрении", потом "утверждена", потом "отклонена", потом "архив" (см. #2). Между кем и кем вставить "Другое"?

**Comment by quellerusco** [comment]
Ненене, имеется в виду не статус заявки, а статус персонажа - там где "студент", "преподаватель" и все такое.

**Comment by Bodigrim** [comment]
Понял. Проверяй.

**Comment by quellerusco** [comment]
Все есть, отлично! Спасибо!
