### ISSUE TITLE
еще один статус

### ISSUE THREAD

**Issue by quellerusco** [Bodigrim/durmstrang#9]
В разделе заявки "Персонаж" в графе "Поступление в Дурмштранг" нужен еще вариант "Не учился в Дурмштранге" и вариант "Другое"
Спасибо

**Comment by Bodigrim** [comment]
А "Я преподаватель" оставить или убрать?

**Comment by quellerusco** [comment]
Оставить.

**Comment by Bodigrim** [comment]
Тогда проверяй.

**Comment by quellerusco** [comment]
есть, спасибо!
